"""Context-safe references to live remote app surfaces (X11 + VNC).

A "surface" is a headless X display on a Pack tab's remote host running one
GUI application, watchable and drivable from the conversation panel. Unlike
images (bytes inline) and videos (bytes on disk, fetched in chunks), a
surface has no bytes at all — its pixels travel over a WebSocket that
bypasses Python entirely. What travels through chat state is only a
*descriptor*: which surface this fold refers to, how big it was, and what it
was running.

That distinction is the whole persistence story. A surface is never revived.
Reopening a month-old conversation renders the same card, `surface_list`
reports the id is gone, and the card says so — no reconnect attempt, no error
path. If a durable artifact is wanted in the record, the model takes a
snapshot, which lands as an ordinary image result via image_tool_result.

The sentinel format deliberately mirrors video_tool_result.py, including its
trailing-quote trimming: the last field has no closing delimiter, so when the
whole string arrives wrapped in the `{"content": [...]}` storage envelope
(the common case — see image_tool_result's docstring) the envelope's own
quote leaks into it and must be cut.
"""

from __future__ import annotations

import re

SENTINEL = "@@ALPACA_SURFACE_RESULT@@"
FIELD_SEP = "@@ALPACA_FIELD@@"

# Surface ids are generated by the supervisor (`srf_` + 8 hex chars). Parsing
# validates the shape so a malformed/truncated result degrades to "not a
# surface" — rendered as ordinary text — rather than producing a card that
# points at nothing.
_SURFACE_ID_RE = re.compile(r"^srf_[0-9a-f]{8}$")
_GEOMETRY_RE = re.compile(r"^(\d{1,5})x(\d{1,5})$")


def encode_surface_result(
    surface_id: str,
    width: int,
    height: int,
    description: str,
) -> str:
    """Encode a surface descriptor. No pixels, by construction."""
    return FIELD_SEP.join(
        (f"{SENTINEL}{surface_id}", f"{width}x{height}", description),
    )


def parse_surface_result(content: str) -> tuple[str, int, int, str] | None:
    """Return ``(surface_id, width, height, description)`` when recognized."""
    idx = content.find(SENTINEL)
    if idx == -1:
        return None
    parts = content[idx + len(SENTINEL) :].split(FIELD_SEP, 2)
    if len(parts) != 3:
        return None
    surface_id, geometry, description = parts
    if _SURFACE_ID_RE.match(surface_id) is None:
        return None
    match = _GEOMETRY_RE.match(geometry)
    if match is None:
        return None
    width, height = int(match.group(1)), int(match.group(2))
    if width <= 0 or height <= 0:
        return None
    quote_idx = description.find('"')
    if quote_idx != -1:
        description = description[:quote_idx].removesuffix("\\")
    return surface_id, width, height, description
